import './globals.css'
import Navbar from '../../components/navbar';

export const metadata = {
  title: "Next.js App",
  description: "Generated by create-next-app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navbar />   {/* Navbar appears on all pages */}
        {children}
      </body>
    </html>
  );
}
